### ISSUE TITLE
getting puppet parser error on epp files

### ISSUE THREAD

**Issue by jgjohn02** [bitzl/vscode-puppet#3]
First of all thank you for a great addition to puppet and visual studio code!

I have  small issue where it looks like when i have an epp file open puppet parser validate is running against it and stating i have an error. If I manually run puppet epp validate against the same file its good, and the file is compiling fine. 

would it be possible to have "puppet epp validate" run against epp and keep "puppet parser validate" against pp?

Thanks!
J

**Comment by bitzl** [comment]
Done and published.
